/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.hkjt.srgk.huiguan.hzshuju;
	
import nc.vo.pub.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class HZGZShuJuVO extends SuperVO {
	private java.lang.String pk_hk_srgk_hg_gz;
	private java.lang.String pk_group;
	private java.lang.String pk_org;
	private java.lang.String pk_org_v;
	private java.lang.String pk_dept;
	private java.lang.String hzdate;
	private nc.vo.pub.lang.UFDouble gz_jine;
	private java.lang.String gz_info;
	private java.lang.String pk_fdept;
	private java.lang.String vdef1;
	private java.lang.String vdef2;
	private java.lang.String vdef3;
	private java.lang.String vdef4;
	private java.lang.String vdef5;
	private String jzfs_pk;
	private Integer uptype;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;
	private String pk_hk_srgk_hg_hzshuju;
	
	
	public String getPk_hk_srgk_hg_hzshuju() {
		return pk_hk_srgk_hg_hzshuju;
	}
	public void setPk_hk_srgk_hg_hzshuju(String pk_hk_srgk_hg_hzshuju) {
		this.pk_hk_srgk_hg_hzshuju = pk_hk_srgk_hg_hzshuju;
	}
	public String getJzfs_pk() {
		return jzfs_pk;
	}
	public void setJzfs_pk(String jzfs_pk) {
		this.jzfs_pk = jzfs_pk;
	}
	public Integer getUptype() {
		return uptype;
	}
	public void setUptype(Integer uptype) {
		this.uptype = uptype;
	}

	public static final String PK_HK_SRGK_HG_GZ = "pk_hk_srgk_hg_gz";
	public static final String PK_GROUP = "pk_group";
	public static final String PK_ORG = "pk_org";
	public static final String PK_ORG_V = "pk_org_v";
	public static final String PK_DEPT = "pk_dept";
	public static final String HZDATE = "hzdate";
	public static final String GZ_JINE = "gz_jine";
	public static final String GZ_INFO = "gz_info";
	public static final String PK_FDEPT = "pk_fdept";
	public static final String VDEF1 = "vdef1";
	public static final String VDEF2 = "vdef2";
	public static final String VDEF3 = "vdef3";
	public static final String VDEF4 = "vdef4";
	public static final String VDEF5 = "vdef5";
			
	/**
	 * 属性pk_hk_srgk_hg_gz的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_hk_srgk_hg_gz () {
		return pk_hk_srgk_hg_gz;
	}   
	/**
	 * 属性pk_hk_srgk_hg_gz的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newPk_hk_srgk_hg_gz java.lang.String
	 */
	public void setPk_hk_srgk_hg_gz (java.lang.String newPk_hk_srgk_hg_gz ) {
	 	this.pk_hk_srgk_hg_gz = newPk_hk_srgk_hg_gz;
	} 	  
	/**
	 * 属性pk_group的Getter方法.属性名：集团
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * 属性pk_group的Setter方法.属性名：集团
	 * 创建日期:
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * 属性pk_org的Getter方法.属性名：组织
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * 属性pk_org的Setter方法.属性名：组织
	 * 创建日期:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	  
	/**
	 * 属性pk_org_v的Getter方法.属性名：组织版本
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org_v () {
		return pk_org_v;
	}   
	/**
	 * 属性pk_org_v的Setter方法.属性名：组织版本
	 * 创建日期:
	 * @param newPk_org_v java.lang.String
	 */
	public void setPk_org_v (java.lang.String newPk_org_v ) {
	 	this.pk_org_v = newPk_org_v;
	} 	  
	/**
	 * 属性pk_dept的Getter方法.属性名：部门
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_dept () {
		return pk_dept;
	}   
	/**
	 * 属性pk_dept的Setter方法.属性名：部门
	 * 创建日期:
	 * @param newPk_dept java.lang.String
	 */
	public void setPk_dept (java.lang.String newPk_dept ) {
	 	this.pk_dept = newPk_dept;
	} 	  
	/**
	 * 属性hzdate的Getter方法.属性名：日期
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public String getHzdate () {
		return hzdate;
	}   
	/**
	 * 属性hzdate的Setter方法.属性名：日期
	 * 创建日期:
	 * @param newHzdate nc.vo.pub.lang.UFDateTime
	 */
	public void setHzdate (String newHzdate ) {
	 	this.hzdate = newHzdate;
	} 	  
	/**
	 * 属性gz_jine的Getter方法.属性名：挂账金额
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getGz_jine () {
		return gz_jine;
	}   
	/**
	 * 属性gz_jine的Setter方法.属性名：挂账金额
	 * 创建日期:
	 * @param newGz_jine nc.vo.pub.lang.UFDouble
	 */
	public void setGz_jine (nc.vo.pub.lang.UFDouble newGz_jine ) {
	 	this.gz_jine = newGz_jine;
	} 	  
	/**
	 * 属性gz_info的Getter方法.属性名：挂账信息
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getGz_info () {
		return gz_info;
	}   
	/**
	 * 属性gz_info的Setter方法.属性名：挂账信息
	 * 创建日期:
	 * @param newGz_info java.lang.String
	 */
	public void setGz_info (java.lang.String newGz_info ) {
	 	this.gz_info = newGz_info;
	} 	  
	/**
	 * 属性pk_fdept的Getter方法.属性名：上级部门
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_fdept () {
		return pk_fdept;
	}   
	/**
	 * 属性pk_fdept的Setter方法.属性名：上级部门
	 * 创建日期:
	 * @param newPk_fdept java.lang.String
	 */
	public void setPk_fdept (java.lang.String newPk_fdept ) {
	 	this.pk_fdept = newPk_fdept;
	} 	  
	/**
	 * 属性vdef1的Getter方法.属性名：自定义项1
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVdef1 () {
		return vdef1;
	}   
	/**
	 * 属性vdef1的Setter方法.属性名：自定义项1
	 * 创建日期:
	 * @param newVdef1 java.lang.String
	 */
	public void setVdef1 (java.lang.String newVdef1 ) {
	 	this.vdef1 = newVdef1;
	} 	  
	/**
	 * 属性vdef2的Getter方法.属性名：自定义项2
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVdef2 () {
		return vdef2;
	}   
	/**
	 * 属性vdef2的Setter方法.属性名：自定义项2
	 * 创建日期:
	 * @param newVdef2 java.lang.String
	 */
	public void setVdef2 (java.lang.String newVdef2 ) {
	 	this.vdef2 = newVdef2;
	} 	  
	/**
	 * 属性vdef3的Getter方法.属性名：自定义项3
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVdef3 () {
		return vdef3;
	}   
	/**
	 * 属性vdef3的Setter方法.属性名：自定义项3
	 * 创建日期:
	 * @param newVdef3 java.lang.String
	 */
	public void setVdef3 (java.lang.String newVdef3 ) {
	 	this.vdef3 = newVdef3;
	} 	  
	/**
	 * 属性vdef4的Getter方法.属性名：自定义项4
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVdef4 () {
		return vdef4;
	}   
	/**
	 * 属性vdef4的Setter方法.属性名：自定义项4
	 * 创建日期:
	 * @param newVdef4 java.lang.String
	 */
	public void setVdef4 (java.lang.String newVdef4 ) {
	 	this.vdef4 = newVdef4;
	} 	  
	/**
	 * 属性vdef5的Getter方法.属性名：自定义项5
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVdef5 () {
		return vdef5;
	}   
	/**
	 * 属性vdef5的Setter方法.属性名：自定义项5
	 * 创建日期:
	 * @param newVdef5 java.lang.String
	 */
	public void setVdef5 (java.lang.String newVdef5 ) {
	 	this.vdef5 = newVdef5;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_hk_srgk_hg_gz";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "hk_srgk_hg_hzshuju_gz";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "hk_srgk_hg_hzshuju_gz";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public HZGZShuJuVO() {
		super();	
	}    
	
	@nc.vo.annotation.MDEntityInfo(beanFullclassName =  "nc.vo.hkjt.srgk.huiguan.hzshuju.HZGZShuJuVO" )
	public IVOMeta getMetaData() {
   		return null;
  	}
} 


